# status code
STATUS_CODE_SUCCESS = 0
STATUS_CODE_NO_RESPONSE = 40000
STATUS_CODE_INVALID_PARAMETER = 40001
STATUS_CODE_PARSING_XML_ERROR = 40002

# error message
MESSAGE_SUCCESS = "OK"
MESSAGE_NO_RESPONSE = "response data is none"
MESSAGE_INVALID_PARAMETER = "no matching data for parameters"
MESSAGE_PARSING_XML_ERROR = "parsing response xml to rule set fail"

B2B_RESPONSE_KEY_RETURN_CODE = "returnCode"
B2B_RESPONSE_KEY_MESSAGE = "message"
B2B_RESPONSE_KEY_MESSAGE_CODE = "messageCode"
B2B_RESPONSE_KEY_MESSAGE_TEXT = "text"
B2B_RESPONSE_KEY_MESSAGE_LOCALIZATION_TEXT = "localizedText"
B2B_RESPONSE_KEY_PAYLOAD = "payload"

# baseRequestTask
RESPONSE_KEY_STATUS_CODE = 'api_ret_code'
RESPONSE_KEY_MESSAGE = 'api_ret_message'
RESPONSE_KEY_DATA = 'data'

# downloadRuleSetTask
RESPONSE_KEY_SUCCESS = 'success'
RESPONSE_KEY_FAIL = 'fail'
DATA_KEY_RULES_NAME = 'rules_name'
DATA_KEY_DOWNLOAD_STATUS = 'status'

# ruleListCompareBuilder
RESPONSE_KEY_ENVIRONMENT_NAME = 'environment_name'
RESPONSE_KEY_ENVIRONMENT_LIST = 'environment_list'
RESPONSE_KEY_DIFF_LIST = 'diff_list'
RESPONSE_KEY_RULESET_FILE_LIST = 'ruleset_file_list'
RESPONSE_KEY_UNION_FILE_LIST = 'union_file_list'


ERROR_MESSAGE_MAP = {
    STATUS_CODE_NO_RESPONSE: MESSAGE_NO_RESPONSE,
    STATUS_CODE_INVALID_PARAMETER: MESSAGE_INVALID_PARAMETER,
    STATUS_CODE_PARSING_XML_ERROR: MESSAGE_PARSING_XML_ERROR,
}

STATUS_MESSAGE_MAP = {
    STATUS_CODE_NO_RESPONSE: MESSAGE_NO_RESPONSE,
    STATUS_CODE_INVALID_PARAMETER: MESSAGE_INVALID_PARAMETER,
    STATUS_CODE_PARSING_XML_ERROR: MESSAGE_PARSING_XML_ERROR,
}