# Region
REGION_APAC = "apac"
REGION_NL = "nl"
REGION_GAS = "gas"
REGION_CORE = "core"

# Time Zone
TINE_ZONE_ASIA_TAIPEI = "Asia/Taipei"
TINE_ZONE_AMSTERDAM = "Europe/Amsterdam"
TIME_ZONE_SERVER = "Asia/Taipei"
TIME_ZONE_BERLIN = "Europe/Berlin"
TIME_ZONE_LONDON = "Europe/London"

TIME_ZONE_SET = {
    REGION_APAC: TINE_ZONE_ASIA_TAIPEI,
    REGION_NL: TINE_ZONE_AMSTERDAM,
    REGION_GAS: TIME_ZONE_BERLIN,
    REGION_CORE: TIME_ZONE_LONDON
}
