# Generated by Django 2.1.1 on 2018-12-18 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('full_name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('icon_file_name', models.CharField(blank=True, default=None, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('full_name', models.CharField(max_length=128)),
                ('b2b_rule_set_client', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('icon_file_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('icon_file_name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('functions', models.ManyToManyField(to='RulesetComparer.Function')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSchedulerInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mail_list', models.TextField()),
                ('interval_hour', models.IntegerField()),
                ('last_proceed_time', models.DateTimeField(null=True)),
                ('next_proceed_time', models.DateTimeField(null=True)),
                ('enable', models.IntegerField()),
                ('base_environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_environment_id', to='RulesetComparer.Environment')),
                ('compare_environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_environment_id', to='RulesetComparer.Environment')),
                ('country_list', models.ManyToManyField(to='RulesetComparer.Country')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_id', to='RulesetComparer.Module')),
            ],
        ),
        migrations.CreateModel(
            name='TestScheduledTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('modules', models.ManyToManyField(to='RulesetComparer.Module')),
            ],
        ),
    ]
