# Generated by Django 2.1.1 on 2018-12-19 08:40

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('RulesetComparer', '0001_initial'),
    ]

    operations = [
    ]
